###
POST http://localhost:9000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "cedula":11223344,
    "nombre":"Frodo Bolson",
    "telefono": 3025251108,
    "direccion":"Carrera 20 # 61BN - 66",
    "email":"z.meza.g@hotmail.com",
    "contraseña": "12345"
}

